WIDTH: 1000
HEIGHT: 600
TIP_WIDTH: 200
ENEMY_MAX_NUM: 30
BULLET_MAX_NUM: 5
ENEMY_INIT_NUM: 5

BG_IMG_PATH: "resource/plane/bg.jfif"

PLAYER:
  IMG_PATH: "resource/plane/player.jpg"
  WIDTH: 100
  HEIGHT: 100
  STEP: 2

BULLET:
  IMG_PATH: "resource/plane/bullet.jfif"
  WIDTH: 10
  HEIGHT: 30
  STEP: 5

ENEMY:
  IMG_PATH: "resource/plane/enemy.jpg"
  WIDTH: 10
  HEIGHT: 30
  X_STEP:
    - 3
    - 5
  Y_STEP:
    - 5
    - 10
